martinrotter/rssguard

resources/desktop/rssguard.desktop

This PR is proposing some changes in the desktop entry file.
*Encoding*
Removed as [deprecated](https://specifications.freedesktop.org/desktop-entry-spec/latest/apc.html) according to the specification.
*X-LXQt-Need-Tray=true*
This key makes RSS Guard start after the panel on LXQt if stated in the desktop entry file to auto start the application. This prevents a crash / core dump that reproducibly takes place otherwise when auto start is enabled and RSS Guard is configured to display the tray icon upon launch. It shouldn't do any harm as it's a custom key according to section [Extending the format](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s11.html) of the underlying specification.
*GenericName*
The text is the same as in key `Comment` and rather matching the …

Improve desktop entry file

---

localization/rssguard-de.ts

This PR is providing the updated German translation. It's sent as PR as Transifex was buggy today and I could neither use its web interface nor download the file.
I added some `<translatorcomment>` tags with notes and questions. You may want to have a look. Also, some additional mnemonics were added in German which I think should be added in the template file / in English as well. These are not commented in the TS file but can of course easily be discovered by the highlighting of e. g. Qt Linguist.

Localization: Update German translation

---

src/main.cpp

On macOS it is customary to not show any icons in menus.

Don't show icons in menus on Mac

---

rssguard.pro
src/gui/dialogs/formmain.cpp
src/main.cpp
src/miscellaneous/disablewindowtabbing.mm

- Disable native window tabbing on macOS. Otherwise macOS automatically adds an item on the View menu to show the system tab bar.
- Hide the menu item to show/hide the menu bar. It has no effect and meaning on macOS.
- Hide the menu item to view full screen. This is handled natively by macOS.

Fix for three GUI issues on macOS

---

src/services/tt-rss/network/ttrssnetworkfactory.cpp

Hello,
I’ve fixed Bug #172 in the branch named “tt-rss/dateError” in my fork.
Unfortunately with this bug one can't use rssguard together with tiny tiny rss. I hope this will help to get rid of it.
Thanx

Solution bug #172

---

rssguard.pro

This is the recommendation of the Icon Theme Specification:
https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#install_icons

Install icons under icons/hicolor/scalable/apps instead of pixmaps

---

localization/rssguard_de.ts
localization/rssguard_en.ts
src/librssguard/gui/settings/settingsfeedsmessages.cpp
src/librssguard/gui/settings/settingsfeedsmessages.ui
src/librssguard/miscellaneous/feedreader.cpp
src/librssguard/miscellaneous/feedreader.h
src/librssguard/miscellaneous/settings.cpp
src/librssguard/miscellaneous/settings.h

I often read articles within RSS Guard and the auto update tends to get in the way by making the program unresponsive, so I thought it would be nice to have an option to postpone them as long as the main window is focused:
I hope I implemented it correctly and followed the coding style. I also updated the translation, although that seems to have reformatted a few things, so I'm not sure if that's okay.

Added option to postpone auto update if window is focused

---

resources/sql.qrc
resources/sql/db_update_mysql_11_12.sql

If Feed's URL is too long, user got error "Feed was not added due to error"

increase length of column Feeds.url in MySQL from 100 to 1000

---

resources/desktop/com.github.rssguard.desktop

Apparently, Qt applications running on GNOME will need this key set, otherwise you won't be able to add them to your Favorites.
A few Qt apps that have `StartupWMClass` set:
* [qBittorrent](https://github.com/qbittorrent/qBittorrent/commit/9ccb4e2781aeeb121e00f3591f640dbb0ca6488c)
* [KeePassXC](https://github.com/keepassxreboot/keepassxc/commit/afe2967473dd6b6e23b81b2dbbab7d5402f71a1b)
And here's the desktop specification: https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html
Before (right clicking RSS Guard):
After:

linux: set StartupWMClass in desktop file

---

resources/rssguard.qrc
resources/skins/nudus/html_adblocked.html
resources/skins/nudus/html_enclosure_every.html
resources/skins/nudus/html_enclosure_image.html
resources/skins/nudus/html_single_message.html
resources/skins/nudus/html_wrapper.html
resources/skins/nudus/metadata.xml
resources/skins/nudus/theme.css

Sorry for opening it at such an early stage, but I have a few questions.
Some examples:
<details> <summary>Click me</summary>
</details>

Add new skin

---

README.md
build.pro
resources/docs/Documentation.md
resources/scripts/github-actions/build-linux-mac.sh
src/librssguard/definitions/definitions.h
src/rssguard/main.cpp

Attempt to complete the #527.
I don't think I can change the `*.ts` files through PR, right?

Use newer name for Mac OS X/OS X -> macOS

---

src/librssguard/miscellaneous/skinfactory.cpp

Since qt6ct can act as the middleman between Qt Fusion and RSS Guard, too.

Allow force dark look for qt6ct

---

resources/skins/nudus-base/html_style_base.scss
resources/skins/nudus-dark/html_style.css
resources/skins/nudus-dark/metadata.xml
resources/skins/nudus-light/html_style.css
resources/skins/nudus-light/metadata.xml

With this commit, if feed's article link is empty (`<link href="" />`), the URL element in article browser won't be displayed.
Feed example:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<feed xmlns="http://www.w3.org/2005/Atom">
...
<entry>
<title type="html">Title</title>
<link href="" />
<updated>2022-01-01T00:00:00+00:00</updated>
<id>id</id>
<summary type="html">
summary
</summary>
</entry>
</feed>
```

Hide URL if `href` attribute is empty (nudus skins)

---

resources/skins/nudus-base/html_style_base.scss
resources/skins/nudus-dark/html_style.css
resources/skins/nudus-light/html_style.css

With this PR, `<pre>` and `<code>` elements in article browser will use system default monospace font. 
(Not tested on Windows.)

Use system default monospace font for code elements (nudus skins)

---

src/librssguard/services/newsblur/newsblurnetwork.cpp

GCC thinks the assignment is ambiguous

Fix build issue in newsblur when compiling with GCC 11.2

---

src/librssguard/gui/settings/settingsgui.cpp
src/librssguard/gui/settings/settingsgui.ui
src/librssguard/miscellaneous/application.cpp
src/librssguard/miscellaneous/settings.cpp
src/librssguard/miscellaneous/settings.h

In a news reading style with many sources and leaving messages unread
the unread message count becomes irrelevant. We already have an option
to disable the count in the icon tray, but not on the task bar. Added a
checkbox to enable/disable the message count on apps task bar icon /
entry.
Chose to put it into a new tab page as we might add more task bar
functionality (progress update, recent articles, etc..).

Add option to control the display of the unread message count on task bar

---

src/librssguard/core/feeddownloader.cpp
src/librssguard/core/feeddownloader.h

Some downloaded feeds contain multiple entries for the same message.
See `http://feeds.feedburner.com/abseilio` for an example that has:
```
<pubDate>2020-09-11T00:00:00-04:00</pubDate>
<link>https://abseil.io/tips/5</link>
--
<pubDate>2020-06-01T00:00:00-04:00</pubDate>
<link>https://abseil.io/tips/5</link>
```
When updating the database for the first time, both messages end up
stored. The following feed updates result in one entry matching the
database, and the second entry having a different creation date. This
makes the second entry always marked as unread.

Remove duplicates from downloaded message list

---

CMakeLists.txt

In the file "filteringexception.h" use the enum "QJSValue::ErrorType",but this enum define in Qt 5.12

Modify min Qt version of Qt5 in CMakeLists

---

resources/skins/nudus-base/html_single_message.html
resources/skins/nudus-base/html_style_base.scss
resources/skins/nudus-dark/html_style.css
resources/skins/nudus-dark/metadata.xml
resources/skins/nudus-light/html_style.css
resources/skins/nudus-light/metadata.xml

EDIT: I decided to make it as a single PR.
First commit is just for history's sake. It fixes the problem when "URL" becomes invisible when window scrollbar is hovered.
In second commit this feature is removed entirely.
@martinrotter, Merge them as **two** separate commits. It would not make sense otherwise.  
I repeat, **Do not squash them.** Please. 
Thanks.

Never hide article URL (nudus skins)

---

resources/desktop/com.github.rssguard.appdata.xml

Should probably fix Flathub not being able to download the screenshot and leaving an empty space instead of the screenshot:

Use the direct URL for the screenshot

---

resources/desktop/io.github.martinrotter.rssguard.metainfo.xml

References: 
- https://freedesktop.org/software/appstream/docs/chap-Metadata.html
- https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/
More details in the commits description.
Validation output using [`appstream-util`](https://people.freedesktop.org/~hughsient/appstream-glib/) 0.8.1:
```bash
$ appstream-util validate-relax resources/desktop/io.github.martinrotter.rssguard.metainfo.xml
resources/desktop/io.github.martinrotter.rssguard.metainfo.xml: OK
```

AppData improvements

---

src/librssguard/services/owncloud/owncloudnetworkfactory.cpp

Processing of mediaThumbnail item as first enclosure and mediaDescription item as replacement content in Nextcloud feeds.
When subscribing to a Youtube channel using Nextcloud News, RSS Guard internal viewer would show no video description or thumbnail. 
This is due to the feed containing all information in the mediaThumbnail and mediaDescription, e.g. see https://www.youtube.com/feeds/videos.xml?channel_id=UCu7_D0o48KbfhpEohoP7YSQ
By processing these items the internal viewer can show all relevant information. (Limit for picture height increased to 300px in RSS Guard settings.)
New:
Previous:

Processing of mediaThumbnail and mediaDescription for Nextcloud feeds

---

src/librssguard/services/owncloud/owncloudnetworkfactory.cpp

Check if enclosureLink starts with https://www.youtube.com/v/ if enclosureMime is empty. Avoid appending an empty png enclosure. 
Removes the empty png in internal viewer. Also the thumbnail would jump to the left in the internal viewer, because the "image/png" would load with a latency, even when cycling through the feed entries. 
This time, I tried to follow ClangFormat and hope I got it right.
Previous:
New:

Avoid empty png enclosure in YouTube feeds with Nextcloud

---

resources/skins/nudus-dark/html_style.css
resources/skins/nudus-dark/html_style.scss
resources/skins/nudus-dark/metadata.xml
resources/skins/nudus-light/metadata.xml

* Both nudus skins: Update fg feed list colors in metadata.xml
Follow up to https://github.com/martinrotter/rssguard/commit/1e28d482fca8d990c7e32fb3021ac0ed4ba15fcf
* nudus-dark only: Making a UI foreground color a bit lighter, because some say it's problematic to tell normal font from bold (https://github.com/martinrotter/rssguard/issues/838). 
I can totally see how it could be difficult to tell apart because the fg color seems a bit too pale, so here we are.

Update new color keys in metadata.xml (nudus skins)

---

resources/skins/nudus-base/html_style_base.scss
resources/skins/nudus-dark/html_style.css
resources/skins/nudus-dark/metadata.xml
resources/skins/nudus-light/html_style.css
resources/skins/nudus-light/metadata.xml

Seeing https://github.com/martinrotter/rssguard/issues/924 I found that, while other articles are just fine, that one article displays poorly in webengine version too.
This commit should fix that.
This patch **does not fix** the #924.
It's a fix for RSS Guard with webengine only.

Set max-width for figure element (nudus skins)

---

src/librssguard/core/messageobject.cpp

This flag is automatically enabled in openSUSE Tumbleweed.

Fix build error with the -Werror=return-type flag

---

.github/workflows/rssguard.yml

Previously, development binaries were uploaded as soon as their build job succeeded.
However, because we build for many operating systems (with different configurations), sometimes a build would succeed on Windows, but not on Linux, for example.
When that happened, the GitHub Releases page for development builds would be missing binaries for some OSes, because we were removing _all_ previous binaries before we even invoked CMake.
Now, we only replace the previous development builds if _all_ build jobs succeed.

CI: Only replace dev builds if all jobs succeed

---

.gitmodules

It's not needed anymore after the recent Transifex -> Crowdin migration.

Remove `transka` git submodule

---

resources/desktop/rssguard.metainfo.xml.in

The specification does not allow them:
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description

Remove `<pre>` tags from Linux's AppData file

---

resources/desktop/rssguard.metainfo.xml.in
resources/scripts/github-actions/build-linux-mac.sh

This PR introduces minor changes to the Linux AppStream metadata file, such as:
- Adding caption to the main screenshot
- Adding a link to the documentation
- Adding a link to the release notes
Additionally, the validation of this file is now done in GitHub Actions using [`appstream-util`](https://man.archlinux.org/man/extra/appstream-glib/appstream-util.1.en).

Linux: AppStream metadata validation and minor changes

---

CMakeLists.txt
docs/source/contrib/compile.md
docs/source/downloads.md
resources/desktop/CMakeLists.txt
src/librssguard/gui/newspaperpreviewer.cpp

That option was renamed to `NO_LITE` in v4.6.0.
Fixes #1242.

Remove remaining references to CMake's old `USE_WEBENGINE` option

---

src/librssguard/miscellaneous/textfactory.cpp

This Brazilian news website called [Tecnoblog](https://tecnoblog.net/) will often begin their articles with the `<details>` tag, providing a short summary for them.
Fixes #1293

Mark articles that begin with `<details>` as HTML

---

resources/desktop/rssguard.metainfo.xml.in
resources/scripts/github-actions/build-linux-mac.sh

These changes are necessary, especially for Flathub, because they've recently replaced the previous validation tool (called [`appstream-util`](https://github.com/hughsie/appstream-glib)) by [`appstreamcli`](https://github.com/ximion/appstream), and so there are new error messages that we have to deal with...

Linux: Fixes for AppStream metadata validation using `appstreamcli`

---

resources/desktop/rssguard.metainfo.xml.in

This probably doesn't matter *that* much, but we should probably follow what the [documentation](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer) recommends:
>It is recommended to use a reverse-DNS name, like `org.gnome` or `io.github.ximion`, or a Fediverse handle (like `@user@example.org`) as ID to achieve a higher chance of uniqueness.
Sorry I set the wrong ID in my previous pull request, by the way... :x

Linux: Update developer ID in AppStream metadata

---

src/librssguard/gui/mediaplayer/libmpv/libmpvbackend.cpp

Starting from version 0.38.0, libmpv stopped using the `libmpv` video output (`vo` option) by default, which ends up causing mpv to spawn its own, separate and detached window, instead of just embedding itself onto RSS Guard's internal media player.
Upstream commit: https://github.com/mpv-player/mpv/commit/0e441525cfc2c0d56b6d4a5fc67016d7e29d1b2c

Force libmpv to use the "libmpv" video output

---

src/librssguard/CMakeLists.txt
src/librssguard/miscellaneous/pluginfactory.cpp

Some distributions use `lib64` for shared libraries. This breaks the plugin search logic.
Added a `-D` define to use the same path as is configured by CMake.

Use the same library search path as the install path on Unix platforms

---

docs/source/features/cli.md

I noticed cli.md is not up to date so here is an update from the --help command (adjusted a bit since threads doc is dynamic).

Update documentation cli.md

---

src/librssguard/database/databasequeries.cpp
src/librssguard/services/abstract/serviceroot.cpp

Hello,
Thanks for developping rssguard.
On FreeBSD, rssguard 4.6.6 does not list any feed entry at all and the following critical errors appears on stderr :
```
time="     0.353" type="critical" -> message-model: Error when setting new msg view query: 'no such column: "%." - should this be a string literal in single-quotes? Unable to execute statement'.
time="     0.353" type="critical" -> message-model: Used SQL select statement: 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN …
```

Fix LIKE statements using double quotes instead of single ones

---

src/librssguard/CMakeLists.txt
src/librssguard/core/feeddownloader.cpp
src/librssguard/database/databasecleaner.cpp
src/librssguard/database/databasedriver.cpp
src/librssguard/gui/dialogs/formmain.cpp
src/librssguard/gui/webviewers/qtextbrowser/textbrowserviewer.cpp
src/librssguard/miscellaneous/application.cpp
src/librssguard/miscellaneous/feedreader.cpp
src/librssguard/miscellaneous/thread.cpp
src/librssguard/miscellaneous/thread.h
src/librssguard/network-web/adblock/adblockmanager.cpp

On a Linux session with Plasma desktop I was having intermittent desktop and software freezes. These freezes were always associated with RSSGuard using 100% of CPU when it does a periodic feed check (~500 feeds).
In order to resolve this we can lower the thread priority of those background threads in order to not compete with interactive system threads. Unfortunately QThread priorities don't actually work on most Linux systems as it attempts to set the process priority which is ignored with SCHED_OTHER (the default scheduler for most systems), see [here](https://man7.org/linux/man-pages/man7/sched.7.html) for more info. Instead we need to use nice values to achieve the same effect (confusingly the Linux documentation ALSO refers to this as process priority despite the fact that it's not …

Run worker pool at lowest thread priority

---

src/librssguard/gui/mediaplayer/libmpv/libmpvwidget.cpp

Fix Qt6 feature checks to ensure the `QT_CONFIG` macro rather than incorrectly checking for the definitions.  `QT_FEATURE_*` are always defined, and they take values 1 or -1 to indicate whether the feature is present or not.  The `QT_CONFIG` macro wraps checking for that, see: https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qtconfigmacros.h?id=f9163ae7a8167daded0798654d99a2e3a5aaa2b5#n60
This fixes build failure when qtbase is built without Wayland support:
```
/tmp/portage/net-news/rssguard-4.8.1/work/rssguard-4.8.1/src/librssguard/gui/mediaplayer/libmpv/libmpvwidget.cpp: In member function ‘v
irtual void LibMpvWidget::initializeGL()’:
/tmp/portage/net-news/rssguard-4.8.1/work/rssguard-4.8.1/src/librssguard/gui/mediaplayer/libmpv/libmpvwidget.cpp:123:60: error: ‘QWayla …
```

fix qt6 feature checks in libmpv

---

src/librssguard/core/feedsmodel.cpp
src/librssguard/miscellaneous/skinfactory.cpp
src/librssguard/miscellaneous/skinfactory.h

A new color customization feature for disabled feeds has been implemented.
The "**Disabled Feeds**" color option is now accessible within the "**Customize predefined colors**" group.
The default display color for disabled feeds is gray.
> **NB :** This feature works seamlessly as a complementary addition to the other committed features, such as [Strikethrough](https://github.com/martinrotter/rssguard/pull/1651) and [Hide](https://github.com/martinrotter/rssguard/pull/1650) Together, these options provide users with a comprehensive set of tools to customize and manage their feed list effectively, catering to different preferences and workflows.
| Enabled   | Disabled |
| ----- | --- |
| ![2 - B_1](https://github.com/user-attachments/assets/00d137e3-5f24-4076-ac86-1320ad108d4e) | ![2 - …

Add new setting for disabled feeds: Custom color options

---

src/librssguard/core/feedsmodel.cpp
src/librssguard/gui/settings/settingsfeedsmessages.cpp
src/librssguard/gui/settings/settingsfeedsmessages.ui
src/librssguard/miscellaneous/settings.cpp
src/librssguard/miscellaneous/settings.h

This add a new checkbox option labeled "**Strikethrough disabled feed titles**" to the user interface.
This feature will apply a strikethrough effect to the titles of disabled feeds in the feed list.
> **NB :** This feature works seamlessly as a complementary addition to the other committed features, such as [Custom color options](https://github.com/martinrotter/rssguard/pull/1652) and [Hide](https://github.com/martinrotter/rssguard/pull/1650) Together, these options provide users with a comprehensive set of tools to customize and manage their feed list effectively, catering to different preferences and workflows.
| Enabled   | Disabled |
| ----- | --- |
| ![2 - B_2](https://github.com/user-attachments/assets/bc7644c3-17ab-4589-af70-0c8ae002a934) |  ![2 - …

Add new setting for disabled feeds: Strikethrough
